/**
 * Utilities class for shared and common components
 */

import React from "react";
import UIAvatarSvg from 'ui-avatar-svg';

/**
 * Use the lib: 'ui-avatar-svg' to generate avator SVG based on initial name
 * @param props User profile information
 * @returns 
 */
export function UIAvatar(props: { initial: string, size?: number, bgColor?: string, textColor?: string }) {
    const [html, setHtml] = React.useState('')

    React.useEffect(() => {
        const svg = new UIAvatarSvg()
        svg.text(props.initial || 'NA')
            .fontFamily('Barlow')
            .fontWeight('bold')
            .size(props.size ?? 64)
            .bgColor(props.bgColor ?? '#ff0000')
            .textColor(props.textColor ?? '#ffffff')

        setHtml(svg.generate());
    }, [props.bgColor, props.initial, props.size, props.textColor])

    // Html injection for SVG code generated by the lib
    return <div dangerouslySetInnerHTML={{ __html: html }} />
}